name: Deploy
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: QEMU
      uses: docker/setup-qemu-action@v1

    - name: Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: login to dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: bump version
      id: tagging
      uses: mathieudutour/github-tag-action@v4.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        file: ./Dockerfile
        tags: 1renatodevops/microservice-kube:${{ steps.tagging.outputs.new_version }}

    - name: install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}

    - name: setup kubectl
      uses: matootie/dokube@v1.3.2
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
        clusterName: k8s-avancadev

    - name: set deployment image
      run: kubectl set image deployment microserviceb microserviceb=1renatodevops/microservice-kube:${{ steps.tagging.outputs.new_version }}

